# Generated by Django 3.2 on 2021-04-23 23:46

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], default='other', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=10)),
                ('municipality', models.CharField(blank=True, max_length=50)),
                ('province', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=patients.models.file_name)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances', to='patients.patient')),
            ],
        ),
    ]
