# Generated by Django 3.2 on 2021-05-16 13:11

import django.core.files.storage
from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210424_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mri',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\ZAHIFER`S THINGS\\DEVELOPMENT\\Tesis\\mri-segmentation\\core\\storage'), upload_to=patients.models.file_name),
        ),
    ]
